name: acsi
channels:
  - pytorch
  - defaults
dependencies:
  - jupyter=1.0.0
  - numpy=1.19.2
  - pip=20.3.3
  - python=3.8.5
  - pytorch=1.7.1
  - pip:
    - matplotlib==3.3.4
    - pandas==1.2.1
    - torchist==0.1.0
    - tqdm==4.56.0
